modLoader = "javafml"

loaderVersion = "${loader_version_range}"

license="${mod_license}"

issueTrackerURL = "https://github.com/NamelessGamer06/Botany-Pots-Mega-Addon-Pack/issues"

[[mods]]

modId = "${mod_id}"

version = "${mod_version}"

displayName = "${mod_name}"

# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"

#logoFile="examplemod.png"

authors="RequiredByCurseForge"

description='''
A Collection of Botany Pot Recipes For All Your Favorite Crops!
'''

# Required Depenincies

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${ mod_id }]]
modId = "bookshelf"
type = "required"
versionRange = "[21.1.81,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "botanypots"
type = "required"
versionRange = "[21.1.41,)"
ordering = "AFTER"
side = "BOTH"

# Mod Compat

[[dependencies.${ mod_id }]]
modId = "rusticdelight"
type = "optional"
versionRange = "[1.5.3,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "mynethersdelight"
type = "optional"
versionRange = "[1.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minersdelight"
type = "optional"
versionRange = "[1.4.1,)"
ordering = "AFTER"
side = "BOTH"